spring.application.name=realista

## DB CONFIG LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/realistadb
spring.datasource.username=realistaDmin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

## DB CONFIG PRE
#spring.datasource.url=jdbc:postgresql://db.railway.internal:5432/realistadb

# Show SQL queries
spring.jpa.show-sql=true
# Format them nicely (optional but recommended)
spring.jpa.properties.hibernate.format_sql=true
# Show the actual parameter values (optional)
logging.level.org.hibernate.orm.jdbc.bind=trace

logging.level.com.realista=DEBUG